version: '3.9'


services:
  postgres:
    image: postgres:latest
    restart: always
    secrets:
      - db-password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=core
      - POSTGRES_USER=core
      - POSTGRES_DB=core_db
    # healthcheck:
    #   test: [ "CMD", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  core: 
    image: core-server:latest
    build:
      context: ./core/
      dockerfile: Dockerfile
      target: final
    environment:
    - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    - POSTGRES_USER=core
    - POSTGRES_DB=core_db
    ports:
      - 8080:8080
    secrets:
      - db-password
    depends_on:
      - postgres    
  app:
    image: ayzblog-app:latest
    build:
      context: ./app/
      dockerfile: Dockerfile 
    environment:
    - REACT_APP_API_URL=https://thecapableone.ayzminy.blog/
    ports:
      - 3000:3000
    depends_on:
      - core
      - postgres
secrets:
  db-password:
    file: db_secrets.txt